apiVersion: v1
kind: Pod
metadata:
  labels:
    name: gdk
  name: gdk
spec:
  containers:
    - image: quay.io/jhayes/golang-docker-kubernetes:latest
      name: gdk
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
